{"name": "test_update_user_with_existing_email", "status": "failed", "statusDetails": {"message": "AssertionError: assert 200 == 403\n +  where 200 = <Response [200]>.status_code", "trace": "access_token = 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MWE5ZTQyOWVkMjgwMDAxYjRmMWUxYSIsImlhdCI6MTcyOTc5OTIzOCwiZXhwIjoxNzI5ODAwNDM4fQ.pfkewTQeOur8fHEBGDhhga_G3VgegHapspkjxeWQGOU'\nexisting_email_data = {'email': 'existinguser@yandex.ru', 'name': 'DuplicateName'}\n\n    def test_update_user_with_existing_email(access_token, existing_email_data):\n        \"\"\"Тест обновления с использованием email, который уже зарегистрирован\"\"\"\n        headers_with_auth = {\n            \"Content-Type\": \"application/json\",\n            \"Authorization\": access_token\n        }\n        response = requests.patch(BASE_URL, json=existing_email_data, headers=headers_with_auth)\n    \n        # Проверяем, что запрос отклонён с кодом 403\n>       assert response.status_code == 403\nE       assert 200 == 403\nE        +  where 200 = <Response [200]>.status_code\n\ntests/test_change_data_user.py:75: AssertionError"}, "description": "Тест обновления с использованием email, который уже зарегистрирован", "start": 1729799237981, "stop": 1729799238196, "uuid": "7d4af30e-849e-4dce-9cbd-c01b7ff6e65a", "historyId": "5649a0af98b1d3c1486db6d64b2c40df", "testCaseId": "5649a0af98b1d3c1486db6d64b2c40df", "fullName": "tests.test_change_data_user#test_update_user_with_existing_email", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_change_data_user"}, {"name": "host", "value": "falcon.local"}, {"name": "thread", "value": "44820-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_change_data_user"}]}