{"name": "test_create_order_with_authorization", "status": "failed", "statusDetails": {"message": "AssertionError: assert 400 == 200\n +  where 400 = <Response [400]>.status_code", "trace": "access_token = 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MWE5ZTQyOWVkMjgwMDAxYjRmMWUxYSIsImlhdCI6MTcyOTc5OTI3MywiZXhwIjoxNzI5ODAwNDczfQ.88zZhdnktWakvTdYNennWfpHU6P2uhOnKipE-6xAnbg'\nvalid_ingredients = ['60d3b41abdacab0026a733c6', '609646e4dc916e00276b2870']\n\n    def test_create_order_with_authorization(access_token, valid_ingredients):\n        \"\"\"Тест создания заказа с авторизацией и валидными ингредиентами\"\"\"\n        headers_with_auth = {\n            \"Content-Type\": \"application/json\",\n            \"Authorization\": access_token\n        }\n        order_data = {\n            \"ingredients\": valid_ingredients\n        }\n        response = requests.post(BASE_URL, json=order_data, headers=headers_with_auth)\n    \n        # Проверяем успешность запроса\n>       assert response.status_code == 200\nE       assert 400 == 200\nE        +  where 400 = <Response [400]>.status_code\n\ntests/test_create_order.py:41: AssertionError"}, "description": "Тест создания заказа с авторизацией и валидными ингредиентами", "start": 1729799273487, "stop": 1729799339785, "uuid": "e8b5a76a-16e8-4180-bc7f-b48df9c56295", "historyId": "fcbe4ad6b733ff1c56056546142bdf0e", "testCaseId": "fcbe4ad6b733ff1c56056546142bdf0e", "fullName": "tests.test_create_order#test_create_order_with_authorization", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "host", "value": "falcon.local"}, {"name": "thread", "value": "44857-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}